Marketplace widget
0xsequence-demos/ingame-marketplace-boilerplate pull request #2
Opened 2024-08-27 20:57 UTC by moskalyk

2024-08-29 09:24 UTC, taylanpince requested changes

2024-08-29 09:24 UTC, taylanpince commented on src/config.ts
> +const googleClientId = '970987756660-35a6tc48hvi8cev9cnknp0iugv9poa23.apps.googleusercontent.com'
Not sure why this is overriding the keys from `.env` – I spent a bunch of time trying to figure out why the preview URL was not working even though it was whitelisted. Can you please switch it back to using `process.env`?

2024-08-29 14:15 UTC, moskalyk commented on src/config.ts
> +const googleClientId = '970987756660-35a6tc48hvi8cev9cnknp0iugv9poa23.apps.googleusercontent.com'
okay done

2024-09-02 12:19 UTC, taylanpince commented
@moskalyk Thanks for updating this to use .env config. I could now test it on the deploy preview with email login. A few feedback items:

1. I don't think we need the Mint and On-ramp tabs. Let's focus on Market (Buy) and Sell.
2. What are the items listed with, and what's the price of each item? I don't see this in the Market tab.
3. Clicking on Purchase crashes the app, this should trigger the purchase flow
4. Can you set a default expiry on the Sell interface? Can be a 1 month later
5. Create Sell Order similarly fails (same error as Purchase Uncaught TypeError: Cannot read properties of undefined (reading 'token'))

2024-09-03 15:35 UTC, moskalyk commented
1. *on-ramp*: So I think we definitely need the on-ramp, because if you're using an embedded wallet, you'll need a way to pay for your transactions. then this gives the added benefit of also on-ramping with a stable currency, so there's much less risk in transactions versus a custom currency. the other option in terms of native fees is doing a custom marketplace wrapper contract that is sponsored, but I don't think most will do this

minting: i'll remove the mint

2. not sure why, but prices are showing for me, only the second time. will try to make it more stable: 
![image](https://github.com/user-attachments/assets/f972887f-c0ef-4cd2-aceb-06e1b5944408)

3. will look into this

4. sure I'll default to 1-month

5. will look into this

2024-11-27 06:30 UTC, bunnybones1 commented
There's a flow change in the design, and we have a simpler SDK to use, so we're closing this PR

2024-11-27 06:30 UTC, closed without merging